using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GenRandom
{
    static class Names
    {
        public static string[] firstNames = { "Oliver", "Jack", "Charlie", "Harry", "Oscar", "Thomas", "Jacob", "Ethan", "Noah", "James", "William", "Joshua", "George", "Leo", "Max", "Henry", "Alfie", "Lucas", "Daniel", "Dylan", "Finley", "Alexander", "Freddie", "Isaac", "Samuel", "Joseph", "Archie", "Muhammad", "Benjamin", "Lewis", "Logan", "Matthew", "Sebastian", "Jake", "Edward", "Zachary", "Aidan", "Luke", "Mason", "Riley", "Ryan", "Elliott", "Toby", "Reuben", "Adam", "Theo", "Connor", "Nathan", "Jayden", "Liam", "Harrison", "Sam", "Michael", "Ollie", "Zac", "Arthur", "Luca", "Ben", "Finn", "Elijah", "Alex", "Tyler", "Jamie", "Blake", "Rhys", "David", "Caleb", "Callum", "Jackson", "Harvey", "Felix", "Jenson", "Jude", "Aaron", "Cameron", "Tommy", "Hugo", "Brody", "Evan", "Gabriel", "Dexter", "Austin", "Nicholas", "Seth", "Harley", "Owen", "Stanley", "Nathaniel", "Rowan", "Rory", "Teddy", "Jason", "Hayden", "Tristan", "Josh", "Jasper", "Bobby", "Frankie", "Tom", "Patrick", "Sophia", "Emily", "Lily", "Olivia", "Amelia", "Isla", "Isabella", "Ava", "Sophie", "Chloe", "Isabelle", "Ella", "Poppy", "Mia", "Evie", "Jessica", "Charlotte", "Grace", "Emma", "Alice", "Ruby", "Eva", "Freya", "Molly", "Scarlett", "Lucy", "Abigail", "Phoebe", "Nur", "Daisy", "Elizabeth", "Hannah", "Florence", "Ellie", "Maryam", "Erin", "Sienna", "Elsie", "Matilda", "Evelyn", "Maya", "Lola", "Bella", "Rosie", "Holly", "Millie", "Annabelle", "Jasmine", "Imogen", "Georgia", "Sarah", "Ivy", "Emilia", "Rose", "Eliza", "Layla", "Mila", "Anna", "Willow", "Amelie", "Maisie", "Summer", "Zara", "Katie", "Megan", "Amber", "Harriet", "Violet", "Madison", "Gracie", "Leah", "Aria", "Thea", "Lara", "Elsa", "Zoe", "Eleanor", "Kayla", "Esme", "Victoria", "Maria", "Iris", "Gabriella", "Lexi", "Harper", "Ariana", "Lacey", "Faith", "Alexis", "Robyn", "Skye", "Alyssa", "Amy", "Elena", "Bethany", "Rebecca", "Lottie", "Clara", "Niamh", "Naomi" };
        public static string[] lastNames = { "Smith", "Jones", "Taylor", "Williams", "Brown", "Davies", "Evans", "Wilson", "Thomas", "Roberts", "Johnson", "Lewis", "Walker", "Robinson", "Wood", "Thompson", "White", "Watson", "Jackson", "Wright", "Green", "Harris", "Cooper", "King", "Lee", "Martin", "Clarke", "James", "Morgan", "Hughes", "Edwards", "Hill", "Moore", "Clark", "Harrison", "Scott", "Young", "Morris", "Hall", "Ward", "Turner", "Carter", "Phillips", "Mitchell", "Patel", "Adams", "Campbell", "Anderson", "Allen", "Cook", "Bailey", "Parker", "Miller", "Davis", "Murphy", "Price", "Bell", "Baker", "Griffiths", "Kelly", "Simpson", "Marshall", "Collins", "Bennett", "Cox", "Richardson", "Fox", "Gray", "Rose", "Chapman", "Hunt", "Robertson", "Shaw", "Reynolds", "Lloyd", "Ellis", "Richards", "Russell", "Wilkinson", "Khan", "Graham", "Stewart", "Reid", "Murray", "Powell", "Palmer", "Holmes", "Rogers", "Stevens", "Walsh", "Hunter", "Thomson", "Matthews", "Ross", "Owen", "Mason", "Knight", "Kennedy", "Butler", "Saunders", "Cole", "Pearce", "Dean", "Foster", "Harvey", "Hudson", "Gibson", "Mills", "Berry", "Barnes", "Pearson", "Kaur", "Booth", "Dixon", "Grant", "Gordon", "Lane", "Harper", "Ali", "Hart", "Mcdonald", "Brooks", "Ryan", "Carr", "Macdonald", "Hamilton", "Johnston", "West", "Gill", "Dawson", "Armstrong", "Gardner", "Stone", "Andrews", "Williamson", "Barker", "George", "Fisher", "Cunningham", "Watts", "Webb", "Lawrence", "Bradley", "Jenkins", "Wells", "Chambers", "Spencer", "Poole", "Atkinson", "Lawson" };
    }
}
